### ISSUE TITLE
Pretrained NYU inference error

### ISSUE THREAD

**Issue by petercheng00** [choyingw/CFCNet#2]
I downloaded the pretrained nyu weights (500.pth), and placed them at `nyu/latest_net_DCCASparseNet.pth`.

When I run `python evaluate.py --name nyu --checkpoints_dir . --train_path ~/nyudepthv2/nyudepthv2/train/ --test_path ~/nyudepthv2/nyudepthv2/val/`
I get:

```
Found 654 images in val folder.
#test images = 654
initialize network with xavier
initialize network with xavier
model [DCCASparseNetModel] was created
loading the model from ./nyu/latest_net_DCCASparseNet.pth
---------- Networks initialized -------------
[Network DCCASparseNet] Total number of parameters : 40.417 M
-----------------------------------------------
Traceback (most recent call last):
  File "evaluate.py", line 95, in <module>
    model.test_depth_evaluation()
  File "/home/pcheng/CFCNet/models/DCCA_sparse_model.py", line 99, in test_depth_evaluation
    self.test_result.evaluate(self.depth_est.data, self.depth_image.data)
  File "/home/pcheng/CFCNet/models/DCCA_sparse_model.py", line 161, in evaluate
    output = output[valid_mask]
IndexError: The shape of the mask [1, 1, 228, 141] at index 3 does not match the shape of the indexed tensor [1, 1, 228, 912] at index 3

```

**Comment by choyingw** [comment]
Hi, thank you for reporting this.

I have updated the training/evaluation procedure for NYU. Please refer to comments about dataloader. If you want to evaluate on NYU, please do the following:
1. Change KITTIDataset to NYUDataset.
2. Change the size at line 235 in DCCA_sparse_networks.py to (224,224)
